# Generated by Django 5.1.4 on 2025-03-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='falta',
            old_name='reposicao_feita',
            new_name='respondida',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='matricula',
        ),
    ]
